name:
  .cargo: î¨
  .docker: î°
  .emacs.d: î¹
  .gradle: î™ 
  .husky: ó°›¢
  .idea: îµ
  .npmrc: îœ
  .pipelines: ó±¢
  .trash: ï‡¸
  .yarn: îš§
  .yarnrc: îš§
  Dockerfile: î°
  Raise: ó°Œ“
  a.out: ï’‰
  assets: î˜
  coverage: î¯
  dist: ó°·Œ
  docker: î°
  dockerfile: î°
  docs: ó°ˆ™
  example: ï”‰
  examples: ï”‰
  git: îœ‚
  gnome: ï¡
  http: ó°–Ÿ
  i3: ïš
  idea: îµ
  iterm2: ï’‰
  k8s: ó±ƒ¾
  kde: ïŒ²
  lua: î˜ 
  migrations: ó°¥
  mocks: ó° ¥
  pg: î®
  setup: ó±›
  src: î«„
  tailwind.config.js: ó±¿
  tailwind.config.ts: ó±¿
  test: ó°™¨
  tests: ó°™¨
  tools: îˆ
  tsconfig.json: ó°›¦
  vscode: ó°˜
  yarnrc: îš§
  zsh: îš‘
extension:
  .npmrc: îœ
  colorscheme: îˆ«
  config.js: î˜•
  config.ts: î˜•
  editorconfig: î™’
  go: î˜§
  hs: î·
  itermcolors: îˆ«
  js: î
  json: ó°˜¦
  md: ó°½›
  rs: ğŸ¦€
  tailwind.config.js: ó±¿
  tailwind.config.ts: ó±¿
  ts: ó°›¦
  yaml: ó°º¥
  yml: ó°º¥
filetype:
  device-block: ó°œ«
  device-char: î˜
  dir: ï„•
  executable: ï’‰
  file: î©»
  pipe: ğŸ“©
  socket: ó°†¨
  special: ï‹œ
  symlink-dir: ï’‚
  symlink-file: ï’
