name:
    .cargo: î¨
    .docker: î°
    .emacs.d: î¹
    .gradle: î™ 
    .husky: ó°›¢
    .idea: îµ
    .npmrc: îœ
    .pipelines: ó±¢
    .trash: ï‡¸
    .yarn: îš§
    .yarnrc: îš§
    Dockerfile: î°
    Raise: ó°Œ“
    a.out: ï’‰
    alacritty: ï’‰
    assets: î˜
    bin: î«¨
    containers: ó°¡¨
    coverage: î¯
    database: îœ†
    db: îœ†
    dist: ó°·Œ
    docker: î°
    dockerfile: î°
    docs: ó°ˆ™
    dotfiles: î˜•
    dygma: ó°ŒŒ
    raise: ó°ŒŒ
    e2e: ó°™¨
    espanso: ó°ŒŒ
    example: ï”‰
    examples: ï”‰
    git: îœ‚
    gnome: ï¡
    http: ó°–Ÿ
    i3: ïš
    idea: îµ
    iterm2: ï’‰
    iterm: ï’‰
    k8s: ó±ƒ¾
    karabiner: ó°ŒŒ
    kde: ïŒ²
    lua: î˜ 
    migrations: ó°¥
    mocks: ó° ¥
    pg: î®
    raycast: ó±“Ÿ
    setup: ó±›
    src: î«„
    stylus: îš•
    tailwind.config.js: ó±¿
    tailwind.config.ts: ó±¿
    test: ó°™¨
    tests: ó°™¨
    tmux: î¯ˆ
    tools: îˆ
    tsconfig.json: ó°›¦
    vscode: ó°˜
    wezterm: ï’‰
    yarnrc: îš§
    yazi: î¸·
    zellij: î¯ˆ
    zsh: îš‘
extension:
    .npmrc: îœ
    colorscheme: îˆ«
    config.js: î˜•
    config.ts: î˜•
    editorconfig: î™’
    go: î˜§
    hs: î·
    itermcolors: îˆ«
    js: î
    json: ó°˜¦
    md: ó°½›
    rs: ğŸ¦€
    tailwind.config.js: ó±¿
    tailwind.config.ts: ó±¿
    toml: îš²
    ts: ó°›¦
    yaml: ó°º¥
    yml: ó°º¥
filetype:
    device-block: ó°œ«
    device-char: î˜
    dir: ï„•
    executable: ï’‰
    file: î©»
    pipe: ğŸ“©
    socket: ó°†¨
    special: ï‹œ
    symlink-dir: ï’‚
    symlink-file: ï’
