name:
  .cargo: î¨
  .docker: î°
  .emacs.d: î¹
  .gradle: î™ 
  .idea: îµ
  .npmrc: îœ
  .pipelines: ó±¢
  .trash: ï‡¸
  .yarn: îš§
  .yarnrc: îš§
  Dockerfile: î°
  a.out: ï’‰
  coverage: î¯
  dist: ó°·Œ
  docker: î°
  dockerfile: î°
  docs: ó°ˆ™
  example: ï”‰
  examples: ï”‰
  git: îœ‚
  http: ó°–Ÿ
  .husky: ó°›¢
  i3: ïš
  idea: îµ
  k8s: ó±ƒ¾
  kde: ïŒ²
  migrations: ó°¥
  mocks: ó° ¥
  pg: î®
  src: î«„
  tailwind.config.js: ó±¿
  tailwind.config.ts: ó±¿
  test: ó°¤‘
  tests: ó°¤‘
  tsconfig.json: ó°›¦
  yarnrc: îš§
extension:
  tailwind.config.js: ó±¿
  tailwind.config.ts: ó±¿
  go: î˜§
  hs: î·
  rs: ğŸ¦€
  js: î
  ts: ó°›¦
  md: ó°½›
  json: ó°˜¦
  .npmrc: îœ
  config.ts: î˜•
  config.js: î˜•
  editorconfig: î™’
  colorscheme: îˆ«
  itermcolors: îˆ«
  yml: ó°º¥
  yaml: ó°º¥
filetype:
  dir: ï„•
  file: î©»
  pipe: ğŸ“©
  socket: ó°†¨
  executable: ï’‰
  symlink-dir: ï’‚
  symlink-file: ï’
  device-char: î˜
  device-block: ó°œ«
  special: ï‹œ
