icons:
    apt: "î½"
    bash: "î•"
    brew: "î¬©"
    cargo: "î¨"
    dnf: "ïŒŠ"
    docker: "ïŒˆ"
    dpkg: "î½"
    fdisk: "ï‚ "
    fish: "î•"
    gh: "ï‚’"
    git: "îœ‚"
    gitui: "îœ‚"
    go: "î˜§"
    helm: "ó±ƒ¾"
    htop: "î®¢"
    hx: "ó°”¤"
    java: "î‰–"
    k9s: "ó±ƒ¾"
    kubectl: "ó±ƒ¾"
    lazydocker: "ïŒˆ"
    lazygit: "îœ‚"
    lf: "ï¼"
    lfcd: "ï¼"
    lsd: "ï¼"
    lvim: "ï¯"
    mage: "î˜§"
    make: "î™³"
    n: "î´"
    nala: "î½"
    node: "î´"
    deno: "ğŸ¦–"
    npm: "î´"
    nu: "î•"
    nvim: "ï¯"
    pacman: "ïŒƒ"
    parted: "ï‚ "
    paru: "ïŒƒ"
    pnpm: "î´"
    python: "îœ¼"
    ranger: "ï¼"
    ruby: "îˆ¾"
    rustc: "î¨"
    rustup: "î¨"
    ssh: "ó°£€"
    tcsh: "î•"
    tig: "îœ‚"
    tmux: "î¯ˆ"
    top: "î®¢"
    topgrade: "ó°š°"
    vim: "ï¯"
    lua: "î˜ "
    yarn: "îš§"
    yay: "ïŒƒ"
    yazi: "î¬¹"
    yum: "ïŒŠ"
    zsh: "î•"
